workflows:
  android-release:
    name: Android Release (AAB)
    max_build_duration: 60
    environment:
      node: 20.18.0
      java: 17
      android_signing:
        - tengri_keystore
      vars:
        PACKAGE_NAME: "co.median.android.bnljzke"
    scripts:
      - name: Install Node dependencies
        script: npm install --legacy-peer-deps

      - name: Build Android release AAB
        script: |
          export GRADLE_OPTS="-Dorg.gradle.jvmargs=-Xmx4096m -Dorg.gradle.daemon=false"
          cd android
          chmod +x ./gradlew
          ./gradlew bundleRelease --no-daemon --max-workers=2

    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/apk/release/*.apk

    publishing:
      email:
        recipients:
          - dagkaranfil@gmail.com
        notify:
          success: true
          failure: true
